---
title:        "Abstract and Introduction" 
author:       "Wilson Wong" 
bibliography: references/references.bib
---

# Abstract

Artificial Intelligence (AI) has rapidly integrated into our world of conflict by reshaping how warfare works, targeting systems, technology in the military is being perform. The 2022 Russia-Ukraine war highlighted greater challenges both weapons and the legal, and governance challenges due to AI, raising concerns about the accountability, rule of war and the adequacy of current international regulatory frameworks. Despite the growing usage of AI these challenges there remains limited empirical analysis of whether international institutions have meaningfully adapted their governance responses considering this conflict. 
This study will look towards Ukraine-Russia war is constitutes a critical juncture in the call of the global governance of military AI. Drawing on theory such as global governances and historical institutionalism, this research analyzes of how international institutions respond to major security shocks and disruption of technology especially on the distinction between hard-law and soft-law regulatory approaches. The study will be using a qualitative research design based on document and thematic analysis of official government documents, reports and statements issued by international institutions between 2015-2025. It will test the hypothesis of intergovernmental organizations produce greater number of AI direction of governance outputs in the two years after invasion started. By examining the content of these outputs this research assesses whether institutional responses represent incremental adaptation or more substantial governances change. The findings aim to contribute to broader debates on AI governance, global security and institutional change in the context of modern warfare. 
